-- smart-todo schema
-- Run in Supabase Dashboard -> SQL Editor, or via `supabase db push` after linking.

-- Tasks
create table if not exists public."Tasks" (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text not null,
  status      text not null default 'todo'
              check (status in ('todo', 'in-progress', 'blocked', 'done')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Dependencies (join: task_id depends on dependency_id)
-- Two FKs to Tasks; PostgREST embedding in the app relies on both
-- (Dependencies!task_id and Tasks!dependency_id).
create table if not exists public."Dependencies" (
  task_id       bigint not null references public."Tasks"(id) on delete cascade,
  dependency_id bigint not null references public."Tasks"(id) on delete cascade,
  created_at    timestamptz not null default now(),
  primary key (task_id, dependency_id)
);

-- auto-touch updated_at on Tasks
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_tasks_updated_at on public."Tasks";
create trigger trg_tasks_updated_at
  before update on public."Tasks"
  for each row execute function public.set_updated_at();

-- No-auth demo: disable RLS + grant CRUD to anon/authenticated.
-- (Supabase enables RLS on new tables by default, which blocks the anon key
-- with no policy -> error 42501. Disabling it makes the demo work.)
-- SECURITY: this exposes full read/write to the publishable key. Fine for a
-- demo; enable RLS + add policies before any real use.
alter table public."Tasks"        disable row level security;
alter table public."Dependencies" disable row level security;

grant all on public."Tasks"        to anon, authenticated;
grant all on public."Dependencies" to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
